"""Initial_schema

Revision ID: 03422c9e1310
Revises: None
Create Date: 2026-08-24 22:22:22.672451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03422c9e1310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
